# Generated by Django 3.2.8 on 2024-03-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='currentfloor',
            field=models.IntegerField(),
        ),
    ]
