# Generated by Django 3.2.8 on 2024-03-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Houseapp', '0002_alter_house_currentfloor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
